apiVersion: v1
kind: Secret
metadata:
  name: sample
  namespace: dev-sample
type: Opaque
stringData:
  APP_KEY: ""
  DB_USERNAME: "dev"
  DB_PASSWORD: "password"
  REDIS_PASSWORD: "null"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  MIX_PUSHER_APP_KEY: "PUSHER_APP_KEY"
